#!/usr/bin/env zsh

# From the TagSpaces documentation:
# "TagSpaces supports tagging of files in a cross platform way. It uses basically the name of the file to save this
# kind of meta information. As an example if you want to add the tags vacation and alps to a image named IMG-2653.jpg,
# the application will simply rename it to IMG-2653[vacation alps].jpg."

set -e

dir=${0:A:h}

. "$dir/first.zsh"

. "$dir/dir.zsh"
. "$dir/file.zsh"
. "$dir/index.zsh"
. "$dir/location.zsh"
. "$dir/tag.zsh"

. "$dir/main.zsh"

tsp "$@"
